

# CFLAGS += -c -Wall -g -lcrypt

# $^ 指目标文件所依赖的文件，如：mytool:$(OBJS)，mytool 要依赖 $(OBJS), 而 $(CC) $(OBJ) -o mytool 是对依赖文件进行编译生成目标文件 mytool 

# $@ 指生成上面的那个目标文件

# $(CC) $^ $(CFLAGS) -o $@ 中下面三句都是一样的，则还可以提取

# % 为通配符

# mytool 所依赖的各个 .o 文件，用通配符 % 表示，对应的 .o 文件需要对应的 .c 文件编译


